services:
  frontend:
    image: paweennutpuyfai/dess-t-frontend:1.0
    ports:
      - "3000:80"
    depends_on:
      - backend-go

  backend-go:
    image: paweennutpuyfai/dess-t-go:2.1
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - backend-python
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: DeSS_T
      POSTGRES_PASSWORD: DeSS_T_491
      POSTGRES_DB: dess_db

  backend-python:
    image: paweennutpuyfai/dess-t-python:2.0
    ports:
      - "5000:5000"

  postgres:
    image: postgis/postgis:15-3.4
    container_name: DeSS_T_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: DeSS_T
      POSTGRES_PASSWORD: DeSS_T_491
      POSTGRES_DB: dess_db
    ports:
      - "5432:5432"
    volumes:
      - DeSS_T:/var/lib/postgresql/data

volumes:
  DeSS_T:
