services:
  frontend:
    image: paweennutpuyfai/dess-t-frontend:6.3
    ports:
      - "3000:80"
    depends_on:
      - backend-go
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend-go:
    image: paweennutpuyfai/dess-t-go:6.3
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      backend-python:
        condition: service_started
    environment:
      DB_HOST: postgres
      UPLOAD_DIR: /uploads
    volumes:
      - ./data/uploads:/uploads

  backend-python:
    image: paweennutpuyfai/dess-t-python:6.0
    ports:
      - "5000:5000"

  postgres:
    image: postgis/postgis:15-3.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DeSS_T"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: DeSS_T_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: DeSS_T
      POSTGRES_PASSWORD: DeSS_T_491
      POSTGRES_DB: dess_db
    ports:
      - "5432:5432"
    volumes:
      - DeSS_T:/var/lib/postgresql/data

volumes:
  DeSS_T:
